version: '3.9'

services:
    price-alert:
        build: ./price-alert
        volumes:
            - ./price-alert:/price-alert
        environment: 
            - PORT=8080
        ports:
            - 5001:8080
    kafka:
        image: lensesio/fast-data-dev:latest
        ports:
            - 5002:3030
        environment:
            - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    consumer:
        build: ./consumer
        volumes:
            - ./consumer:/consumer
    producer:
        build: ./producer
        volumes:
            - ./producer:/producer